### ISSUE TITLE
fix deprecation warning

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/biomarker-catalog#65]
Problem: 
```
`Warning: `summarize_vars()` was deprecated in tern 0.8.5.9010.
ℹ Please use `analyze_vars()` instead.`
```

To do:
Use `analyze_vars()` instead.

**Comment by jeffreyCarlLong** [comment]
This issue has been fixed in `gh pr checkout 68`.

The function summarize_vars() has been deprecated and no longer works. It was used in tables DT1, DT2, and TET1. A new function analyze_vars() is a renamed version of summarize_vars(). All occurrences of the deprecated function have been replaced in this pull request.

[https://github.com/search?q=repo%3Ainsightsengineering%2Fbiomarker-catalog%20summarize_vars&type=code](https://github.com/search?q=repo%3Ainsightsengineering%2Fbiomarker-catalog%20summarize_vars&type=code)

7 files are updated with 9 occurrences.
